### ISSUE TITLE
订阅的时候报错

### ISSUE THREAD

**Issue by 2723659854** [hyperf/nsq#5]
"hyperf/nsq": "2.2.33",
订阅的时候报错，传的是一个字符串”D_PROTOCOL“，执行Json::decode($this->getPayload())就会报错。
报错内容：
```
[ERROR] Hyperf\Utils\Exception\InvalidArgumentException: Syntax error(4) in /data/project/hyper_pool/vendor/hyperf/utils/src/Codec/Json.php:51
Stack trace:
#0 /data/project/hyper_pool/vendor/hyperf/nsq/src/Subscriber.php(79): Hyperf\Utils\Codec\Json::decode()
#1 /data/project/hyper_pool/vendor/hyperf/nsq/src/Pool/NsqConnection.php(68): Hyperf\Nsq\Subscriber->getJsonPayload()
#2 /data/project/hyper_pool/vendor/hyperf/pool/src/KeepaliveConnection.php(91): Hyperf\Nsq\Pool\NsqConnection->getActiveConnection()
#3 /data/project/hyper_pool/vendor/hyperf/pool/src/KeepaliveConnection.php(110): Hyperf\Pool\KeepaliveConnection->reconnect()
#4 /data/project/hyper_pool/vendor/hyperf/nsq/src/Nsq.php(154): Hyperf\Pool\KeepaliveConnection->call()
#5 /data/project/hyper_pool/vendor/hyperf/nsq/src/Nsq.php(113): Hyperf\Nsq\Nsq->call()
#6 /data/project/hyper_pool/vendor/hyperf/nsq/src/ConsumerManager.php(142): Hyperf\Nsq\Nsq->subscribe()
#7 /data/project/hyper_pool/vendor/hyperf/process/src/AbstractProcess.php(134): class@anonymous->handle()
#8 {main}
```

**Comment by huangzhhui** [comment]
贴复现代码

**Comment by alaric8** [comment]
我也是卧槽
